In [33]:
import os, sys,csv
import numpy as np
import pandas as pd
import libsumo
import xml.etree.ElementTree as ET

In [160]:
def generateDataframe(xmlFile):
    parse_xml = ET.parse('myTrace.xml')
    root = parse_xml.getroot()
    vehicles_id_array = {}

    for i in root:
        for attrib in i:
            if attrib.attrib['id'] in vehicles_id_array:
                continue
            else:
                vehicles_id_array[attrib.attrib['id']] = {"x":[],"y":[],"startTime":[],"endTime":0,"isStart":False,"isArrive":False}


    for i in root:
        for attrib in i:
                if attrib.attrib['id'] in vehicles_id_array:
                    vehicles_id_array[attrib.attrib['id']]['x'].append(attrib.attrib['x'])
                    vehicles_id_array[attrib.attrib['id']]['y'].append(attrib.attrib['y'])

    e=0
    for v_id in vehicles_id_array:
        e=0
        for i in root:
            for attrib in i:
                if attrib.attrib['id'] == v_id:
                    vehicles_id_array[attrib.attrib['id']]['endTime'] = e
                    e=e+1
                    break

    with open('dataset_to_train.csv', 'w', newline='') as file:
        writer = csv.writer(file)        
        start_id = 0
        field = ["interaction","vehicle_id","x_start","y_start","x_end","y_end","startTime","arriveTime"]
        writer.writerow(field)
    
        k=0
        for v_id in vehicles_id_array:
            x_coordinate_start = []
            y_coordinate_start = []
            x_coordinate_end = []
            y_coordinate_end = []
            start_time_coord = 0
            arrive_time_coord = []
            vehicle_id = None
            for index in testowy_df.index:
                if int(testowy_df['vehicle_id'][index]) == int(v_id):
                    start_time_coord = testowy_df['startTime'][index]
            for i in root:
                for attrib in i:
                    if attrib.attrib['id'] == v_id:
                        writer.writerow([int(float(i.attrib['time'])),attrib.attrib['id'],
                                        vehicles_id_array[attrib.attrib['id']]['x'][0],
                                        vehicles_id_array[attrib.attrib['id']]['y'][0],
                                        vehicles_id_array[attrib.attrib['id']]['x'][-1],
                                        vehicles_id_array[attrib.attrib['id']]['y'][-1],
                                        start_time_coord,
                                        start_time_coord + vehicles_id_array[attrib.attrib['id']]['endTime']])

    data = pd.read_csv('dataset_to_train.csv')
    data.sort_values("interaction", axis=0, ascending=True,inplace=True, na_position='first')
    data.sort_values("startTime", axis=0, ascending=True,inplace=True, na_position='first')
    data.to_csv('dataset_to_train.csv', index=False)
    data = pd.read_csv('dataset_to_train.csv')
    
    return data

In [138]:
parse_xml = ET.parse('myTrace.xml')
root = parse_xml.getroot()

In [140]:
vehicles_id_array = {}

for i in root:
    for attrib in i:
            if attrib.attrib['id'] in vehicles_id_array:
                continue
            else:
                vehicles_id_array[attrib.attrib['id']] = {"x":[],"y":[],"startTime":[],"endTime":0,"isStart":False,"isArrive":False}

{'x': [], 'y': [], 'startTime': [], 'endTime': 0, 'isStart': False, 'isArrive': False}

In [142]:
for i in root:
    for attrib in i:
            if attrib.attrib['id'] in vehicles_id_array:
                vehicles_id_array[attrib.attrib['id']]['x'].append(attrib.attrib['x'])
                vehicles_id_array[attrib.attrib['id']]['y'].append(attrib.attrib['y'])

In [143]:
e=0
for v_id in vehicles_id_array:
    e=0
    for i in root:
        for attrib in i:
            if attrib.attrib['id'] == v_id:
                vehicles_id_array[attrib.attrib['id']]['endTime'] = e
                e=e+1
                break

In [158]:
with open('dataset_to_train.csv', 'w', newline='') as file:
    writer = csv.writer(file)        
    start_id = 0
    field = ["interaction","vehicle_id","x_start","y_start","x_end","y_end","startTime","arriveTime"]
    writer.writerow(field)

    k=0
    for v_id in vehicles_id_array:
        x_coordinate_start = []
        y_coordinate_start = []
        x_coordinate_end = []
        y_coordinate_end = []
        start_time_coord = 0
        arrive_time_coord = []
        vehicle_id = None
        for index in testowy_df.index:
            if int(testowy_df['vehicle_id'][index]) == int(v_id):
                start_time_coord = testowy_df['startTime'][index]
        for i in root:
            for attrib in i:
                if attrib.attrib['id'] == v_id:
                    writer.writerow([int(float(i.attrib['time'])),attrib.attrib['id'],
                                    vehicles_id_array[attrib.attrib['id']]['x'][0],
                                    vehicles_id_array[attrib.attrib['id']]['y'][0],
                                    vehicles_id_array[attrib.attrib['id']]['x'][-1],
                                    vehicles_id_array[attrib.attrib['id']]['y'][-1],
                                    start_time_coord,
                                    start_time_coord + vehicles_id_array[attrib.attrib['id']]['endTime']])

data = pd.read_csv('dataset_to_train.csv')
data.sort_values("interaction", axis=0, ascending=True,inplace=True, na_position='first')
data.sort_values("startTime", axis=0, ascending=True,inplace=True, na_position='first')
data.to_csv('dataset_to_train.csv', index=False)

2880
9222
12901
339
15101
2934
9022
9515
2115
14987
10127
1919
14245
665
16130
6541
282
15960
6854
5036
11796
14389
2653
4118
12932
14

In [162]:
testowy_df = pd.read_csv("test_df.csv")

def change_start_time(df):
    max = df['vehicle_id'].max()+1
    newdf = np.random.randint(0,16400,size=(max, 1))
    return newdf
    
testowy_df['startTime'] = change_start_time(testowy_df)

testowy_df = testowy_df.sort_values(by=['startTime'])

def SUMO_RUN(test_df):
   if 'SUMO_HOME' in os.environ:
    sys.path.append(os.path.join(os.environ['SUMO_HOME'], 'tools')) 

    with open('test.route.xml', 'w', newline='') as file:
        file.write("<routes>\n")
        file.write('\t<vType id="CAR1" accel="0.8" decel="4" sigma="0.3" lenght="5" color="1,1,0" />\n')
        file.write('\t<route id="route0" color="1,1,0" edges="225118922#2 225118915#0 225118915#1 225118915#2 225118915#3 225118928 225118929#0 225118929#1 225118920#0 225118920#1 225118912 225118913 225118923 225118924#0 225118924#1 225118924#2 225118924#3 7973801#0 7973801#1 7973801#2 255596831#0 255596831#1 255596825#0 255596825#1 255596825#2 222825379#0 222825379#1 222825376 1225481836 744467798#0 744467798#1 730599653#0 730599653#1 730599653#2 495859913 730599651 730599650 730599649 322625232#0 322625232#1 322625232#2 922043208 922043207 744475266 255596827#0 255596827#1 255596827#2 255596827#3 168190618#0 168190618#1 168190616#0 168190616#1 627806961#0 627806961#1 627806961#2 733861039 733861038#0 733861038#1 44625089#0 44625089#1 44625089#2 44625089#3 44625089#4 44625089#5 44625089#6 343501971#0 343501971#1 343501971#2 343501971#3 216830048 89215696 216830042#0 216830042#1 216830042#2 -172993580#27 -172993580#26 -172993580#25 -172993580#24 -172993580#23 -172993580#22 -172993580#21 -172993580#20 -172993580#19 -172993580#18 -172993580#17 -172993580#16 -172993580#15 -172993580#14 -172993580#13 -172993580#12 -172993580#11 -172993580#10 -172993580#9 -172993580#8 -172993580#7 -172993580#6 -172993580#5 -172993580#4 -172993580#3 -172993580#2 -172993580#1 -172993580#0 172993583 272410205 266142483#0 266142483#1 266142483#2 172993576 216830065 216830069#0 216830069#1 216830069#2 266142462" /> \n')
        file.write('\t<route id="route1" color="1,0,1" edges="-172995254#1 -172995254#0 -1095883649#2 -1095883649#1 -1095883649#0 -216263062#2 -216263062#1 -216263062#0 216263059#0 216263059#1 216263059#2 216263059#3 222825342 1225481836 744467798#0 744467798#1 730599653#0 730599653#1 730599653#2 202895995#0 202895995#1 173116373#0 173116373#1 223256101#0 223256101#1 223256101#2 223256101#3 223256101#4 223256101#5 223256101#6 223256101#7 223256101#8 223256101#9 223256101#10 223256101#11 223256101#12 223256101#13 223256101#14 223256101#15 223256101#16 223256101#17 223256101#18 223256101#19 223256101#20 223256101#21 222825341#0 222825341#1 222825341#2 222825341#3 222825341#4 222825341#5 222825341#6 222825341#7 222825341#8 222825341#9 504692926#0 504692926#1 504692926#2 247887453#0 247887453#1 247887453#2 791024988#0 791024988#1 791024988#2 791024988#3 "/> \n')
        file.write('\t<route id="route2" color="1,0,1" edges="-194796165#2 -194796165#1 -194796165#0 -172993056#7 -172993056#6 -172993056#5 -172993056#4 -172993056#3 -172993056#2 -172993056#1 -172993056#0 -994014110 -994014111#1 -994014111#0 131230797#0 131230797#1 131230797#2 131230795#0 131230795#1 224021297#0 224021297#1 224021297#2 168190616#0 168190616#1 167625838#0 167625838#1 44625072#0 44625072#1 44625072#2 44625072#3 255596832#0 255596832#1 255596832#2 255596832#3 255596818 255596820 255596822#0 255596822#1 222825378#0 222825378#1 495859914#0 495859914#1 495859914#2 222825377" /> \n')

        
        for index in testowy_df.index:
            if index <= 20:
                file.write('\t<vehicle id="' + str(testowy_df['vehicle_id'][index]) + '" route="route0" type="CAR1" depart="' + str(testowy_df['startTime'][index]) + '" color="1,1,0" /> \n')
            else:
                file.write('\t<vehicle id="' + str(testowy_df['vehicle_id'][index]) + '" route="route1" type="CAR1" depart="' + str(testowy_df['startTime'][index]) + '" color="1,0,0" /> \n')
        file.write("\n</routes>")
    os.system("sumo -c production.sumocfg --fcd-output myTrace.xml")

    return generateDataframe("myTrace.xml")
       
SUMO_RUN(testowy_df)

Step #10000.00 (0ms ?*RT. ?UPS, vehicles TOT 27 ACT 1 BUF 0)                               p #9100.00 (0ms ?*RT. ?UPS, vehicles TOT 23 ACT 1 BUF 0)

,interaction,vehicle_id,x_start,y_start,x_end,y_end,startTime,arriveTime
0,867,16,22.029442,50.023306,22.005091,50.019495,867,1333
1,1183,16,22.029442,50.023306,22.005091,50.019495,867,1333
2,1182,16,22.029442,50.023306,22.005091,50.019495,867,1333
3,1181,16,22.029442,50.023306,22.005091,50.019495,867,1333
4,1180,16,22.029442,50.023306,22.005091,50.019495,867,1333
...,...,...,...,...,...,...,...,...
8831,9796,14,22.029442,50.023306,22.013078,50.028531,9699,9999
8832,9794,14,22.029442,50.023306,22.013078,50.028531,9699,9999
8833,9793,14,22.029442,50.023306,22.013078,50.028531,9699,9999
8834,9998,14,22.029442,50.023306,22.013078,50.028531,9699,9999
8835,9999,14,22.029442,50.023306,22.013078,50.028531,9699,9999